### ISSUE TITLE
unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by gisms** [fmpfeifer/hikextractor#1]
Hi!!

I am trying to use de hikextractor, with phyton 3.8, getting this error:

HD Signature: HIKVISION@HANGZHOU
Filesystem version: HIK.2011.03.08
HD Capacity: 500107862016 bytes
Data block size: 1073741824 bytes
Time System Init: 2021-09-22 20:57

Channel 01: 99 video blocks
Channel 02: 119 video blocks
Channel 03: 107 video blocks
Channel 04: 124 video blocks
Channel 255: 16 video blocks
Traceback (most recent call last):
  File "hikextractor.py", line 431, in <module>
    export_all_videos(source, dest_folder)
  File "hikextractor.py", line 350, in export_all_videos
    entrylist = sorted(entrylist, key=sortkey)
  File "hikextractor.py", line 348, in sortkey
    return f"{x.start_timestamp:%Y%m%d%H%M}-{x.channel:02d}"
TypeError: unsupported format string passed to NoneType.__format__

any suggestions?

**Comment by fmpfeifer** [comment]
hi, could you please try again with the last commit d7d915a0b5c26bb097340cfafdead87bc090f7bc?
I think it would fix it.

Thanks for reporting

**Comment by gisms** [comment]
ok, I will try and give you feedback.

**Comment by gisms** [comment]
Hi!

The reported error has been fixed.

But now i am facing this problem.


_Channel 01: 99 video blocks
Channel 02: 119 video blocks
Channel 03: 107 video blocks
Channel 04: 124 video blocks
Channel 255: 14 video blocks

Exporting footage for channel 01, block being recorded.
[NULL @ 000001e490ba3dc0] PPS id out of range: 0
[hevc @ 000001e490ba3dc0] PPS id out of range: 0
    Last message repeated 8 times
Too many packets buffered for output stream 0:0.
Traceback (most recent call last):
  File "hikextractor.py", line 306, in export_file
    export_footage_from_block(datablock, ffmpeg.stdin)
  File "hikextractor.py", line 281, in export_footage_from_block
    outfile.write(datablock[start_offset:end_offset])
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hikextractor.py", line 433, in <module>
    export_all_videos(source, dest_folder)
  File "hikextractor.py", line 377, in export_all_videos
    export_file(
  File "hikextractor.py", line 307, in export_file
    ffmpeg.communicate()
  File "C:\Users\g\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 914, in __exit__
    self.stdin.close()
OSError: [Errno 22] Invalid argument_

Any suggestions?

**Comment by fmpfeifer** [comment]
it looks like ffmpeg is having a hard time trying to decode the video stream. Maybe it is corrupted.
Are you using the latest version o ffmpeg?

I pushed a commit adding a switch to ffmpeg to instruct it to ignore errors in input file. Can you give it a try?
Thanks

**Comment by gisms** [comment]
Same problem:

Channel 01: 99 video blocks
Channel 02: 119 video blocks
Channel 03: 107 video blocks
Channel 04: 124 video blocks
Channel 255: 14 video blocks

Exporting footage for channel 01, block being recorded.
[NULL @ 0000025a29324740] PPS id out of range: 0
[hevc @ 0000025a29324740] PPS id out of range: 0
    Last message repeated 8 times
Too many packets buffered for output stream 0:0.
Traceback (most recent call last):
  File "hikextractor.py", line 308, in export_file
    export_footage_from_block(datablock, ffmpeg.stdin)
  File "hikextractor.py", line 281, in export_footage_from_block
    outfile.write(datablock[start_offset:end_offset])
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hikextractor.py", line 435, in <module>
    export_all_videos(source, dest_folder)
  File "hikextractor.py", line 379, in export_all_videos
    export_file(
  File "hikextractor.py", line 309, in export_file
    ffmpeg.communicate()

Is the code passing specific settings to ffmpeg convert? would you be able to generate a commit without calling the ffmpeg conversion? because then I could try different parameters with ffmpeg ....

**Comment by gisms** [comment]
I tried with another script, but ffmpeg is not being able to decode as well. I guess the data it is corrupted. Thank u for your help.

**Comment by fmpfeifer** [comment]
> Same problem:
> 
> Channel 01: 99 video blocks Channel 02: 119 video blocks Channel 03: 107 video blocks Channel 04: 124 video blocks Channel 255: 14 video blocks
> 
> Exporting footage for channel 01, block being recorded. [NULL @ 0000025a29324740] PPS id out of range: 0 [hevc @ 0000025a29324740] PPS id out of range: 0 Last message repeated 8 times Too many packets buffered for output stream 0:0. Traceback (most recent call last): File "hikextractor.py", line 308, in export_file export_footage_from_block(datablock, ffmpeg.stdin) File "hikextractor.py", line 281, in export_footage_from_block outfile.write(datablock[start_offset:end_offset]) BrokenPipeError: [Errno 32] Broken pipe
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "hikextractor.py", line 435, in export_all_videos(source, dest_folder) File "hikextractor.py", line 379, in export_all_videos export_file( File "hikextractor.py", line 309, in export_file ffmpeg.communicate()
> 
> Is the code passing specific settings to ffmpeg convert? would you be able to generate a commit without calling the ffmpeg conversion? because then I could try different parameters with ffmpeg ....

Yes, the parameters passed to ffmpeg are listed in lines 290-304 of hikextractor.py:
```python
            ["ffmpeg",
            "-err_detect",
            "ignore_err",
            "-i",
            "-",
            "-c:v",
            "copy",
            "-bsf:v",
            "filter_units=pass_types=1-5",
            "-aspect",
            "4/3",
            "-loglevel",
            "error",
            "-stats",
            filename,
        ]
```

I'm closing this issue, feel free to open a new one if needed. Thanks
